version: '3.9'

services:
  eureka-server:
    image: neujxj/springcloud:v1.0
    container_name: eureka-server
    ports:
      - "8761:8761"
    volumes:
      - eureka-data:/data

  application:
    image: application:1
    container_name: application
    environment:
      - SPRING_APPLICATION_NAME=application
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

volumes:
  eureka-data: